spring.application.name=chat-app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= kaito_oki
spring.datasource.password= avl1874
spring.flyway.baselineOnMigrate=true